import { onCall } from 'firebase-functions/v2/https';
import * as admin from 'firebase-admin';
import { CVParser } from '../services/cvParser';
import { PIIDetector } from '../services/piiDetector';
import { corsOptions } from '../config/cors';

export const processCV = onCall(
  {
    timeoutSeconds: 300,
    memory: '2GiB',
    ...corsOptions,
    secrets: ['ANTHROPIC_API_KEY']
  },
  async (request) => {
    // Check authentication
    if (!request.auth) {
      throw new Error('User must be authenticated to process CV');
    }

    const { jobId, fileUrl, mimeType, isUrl } = request.data;

    if (!jobId || (!fileUrl && !isUrl)) {
      throw new Error('Missing required parameters');
    }

    try {
      // Update job status
      await admin.firestore()
        .collection('jobs')
        .doc(jobId)
        .update({
          status: 'processing',
          updatedAt: admin.firestore.FieldValue.serverTimestamp()
        });

      // Get job data to retrieve user instructions
      const jobDoc = await admin.firestore()
        .collection('jobs')
        .doc(jobId)
        .get();
      
      const jobData = jobDoc.data();
      const userInstructions = jobData?.userInstructions;

      // Initialize CV parser
      const apiKey = process.env.ANTHROPIC_API_KEY;
      if (!apiKey) {
        throw new Error('Anthropic API key not configured');
      }
      
      const parser = new CVParser(apiKey);
      let parsedCV;

      if (isUrl) {
        // Parse from URL
        parsedCV = await parser.parseFromURL(fileUrl, userInstructions);
      } else {
        // Download file from storage
        const bucket = admin.storage().bucket();
        
        // Extract the file path from the download URL
        // The URL format is: https://firebasestorage.googleapis.com/v0/b/{bucket}/o/{encoded-path}?alt=media&token=...
        const urlObj = new URL(fileUrl);
        const pathMatch = urlObj.pathname.match(/\/o\/(.+)$/);
        if (!pathMatch) {
          throw new Error('Invalid storage URL format');
        }
        
        // Decode the file path
        const filePath = decodeURIComponent(pathMatch[1]);
        console.log('Downloading file from path:', filePath);
        
        const file = bucket.file(filePath);
        const [buffer] = await file.download();
        
        // Parse the CV
        parsedCV = await parser.parseCV(buffer, mimeType, userInstructions);
      }

      // Detect PII
      const piiDetector = new PIIDetector(apiKey);
      const piiResult = await piiDetector.detectAndMaskPII(parsedCV);

      // Save parsed data with PII information
      await admin.firestore()
        .collection('jobs')
        .doc(jobId)
        .update({
          status: 'analyzed',
          parsedData: parsedCV,
          piiDetection: {
            hasPII: piiResult.hasPII,
            detectedTypes: piiResult.detectedTypes,
            recommendations: piiResult.recommendations
          },
          privacyVersion: piiResult.maskedData,
          updatedAt: admin.firestore.FieldValue.serverTimestamp()
        });

      // Check if this is a quick create job
      // (we already have jobData from earlier)
      
      // If quick create, automatically generate CV
      if (jobData?.quickCreate || jobData?.settings?.applyAllEnhancements) {
        // Update status to generating
        await admin.firestore()
          .collection('jobs')
          .doc(jobId)
          .update({
            status: 'generating',
            updatedAt: admin.firestore.FieldValue.serverTimestamp()
          });
        
        // For now, create a simple generated CV
        // TODO: Implement actual CV generation with templates
        const generatedCV = {
          html: `<html><body><h1>${parsedCV.personalInfo.name}</h1><p>Professional CV generated by CVPlus</p></body></html>`,
          pdfUrl: `https://storage.googleapis.com/cvplus.appspot.com/generated/${jobId}/cv.pdf`,
          docxUrl: `https://storage.googleapis.com/cvplus.appspot.com/generated/${jobId}/cv.docx`
        };
        
        // Update job to completed
        await admin.firestore()
          .collection('jobs')
          .doc(jobId)
          .update({
            status: 'completed',
            generatedCV,
            updatedAt: admin.firestore.FieldValue.serverTimestamp()
          });
      }

      return {
        success: true,
        jobId,
        parsedData: parsedCV
      };

    } catch (error: any) {
      console.error('Error processing CV:', error);
      
      // Update job status to failed
      await admin.firestore()
        .collection('jobs')
        .doc(jobId)
        .update({
          status: 'failed',
          error: error.message,
          updatedAt: admin.firestore.FieldValue.serverTimestamp()
        });

      throw new Error(`Failed to process CV: ${error.message}`);
    }
  });