name: Dependency Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * 1' # Weekly on Monday at 9am

jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run dependency validation
      run: ./scripts/validate-dependencies-enhanced.sh --no-fix
    
    - name: Upload reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: dependency-reports
        path: reports/
    
    - name: Comment PR
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('reports/dependency-report.md', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '## ⚠️ Dependency Validation Failed\n\n' + report
          });
